namespace Poly
{
    public static class Mime
    {
        public static readonly Dictionary<string, string> Types = new()
        {
            { ".7z", "application/x-7z-compressed" },
            { ".aac", "audio/x-aac" },
            { ".bin", OctetStream },
            { ".bz", "application/x-bzip" },
            { ".bz2", "application/x-bzip2" },
            { ".css", "text/css" },
            { ".csv", "text/csv" },
            { ".dmg", OctetStream },
            { ".doc", "application/msword" },
            { ".docm", "application/vnd.ms-word.document.macroenabled.12" },
            { ".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
            { ".exe", "application/x-msdownload" },
            { ".flv", "video/x-flv" },
            { ".gif", "image/gif" },
            { ".h261", "video/h261" },
            { ".h263", "video/h263" },
            { ".h264", "video/h264" },
            { ".htm", "text/html" },
            { ".html", "text/html" },
            { ".ico", "image/x-icon" },
            { ".jpe", "image/jpeg" },
            { ".jpeg", "image/jpeg" },
            { ".jpg", "image/jpeg" },
            { ".jpgm", "video/jpm" },
            { ".jpgv", "video/jpeg" },
            { ".jpm", "video/jpm" },
            { ".js", "application/javascript" },
            { ".json", JSON },
            { ".log", PlainText },
            { ".m1v", "video/mpeg" },
            { ".m21", "application/mp21" },
            { ".m2a", "audio/mpeg" },
            { ".m2v", "video/mpeg" },
            { ".m3a", "audio/mpeg" },
            { ".m3u", "audio/x-mpegurl" },
            { ".m3u8", "application/vnd.apple.mpegurl" },
            { ".m4u", "video/vnd.mpegurl" },
            { ".m4v", "video/x-m4v" },
            { ".mid", "audio/midi" },
            { ".midi", "audio/midi" },
            { ".mov", "video/quicktime" },
            { ".movie", "video/x-sgi-movie" },
            { ".mp2", "audio/mpeg" },
            { ".mp21", "application/mp21" },
            { ".mp2a", "audio/mpeg" },
            { ".mp3", "audio/mpeg" },
            { ".mp4", "video/mp4" },
            { ".mp4a", "audio/mp4" },
            { ".mp4s", "application/mp4" },
            { ".mp4v", "video/mp4" },
            { ".mpe", "video/mpeg" },
            { ".mpeg", "video/mpeg" },
            { ".mpg", "video/mpeg" },
            { ".mpg4", "video/mp4" },
            { ".mpga", "audio/mpeg" },
            { ".oga", "audio/ogg" },
            { ".ogg", "audio/ogg" },
            { ".ogv", "video/ogg" },
            { ".png", "image/png" },
            { ".pps", "application/vnd.ms-powerpoint" },
            { ".ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12" },
            { ".ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow" },
            { ".ppt", "application/vnd.ms-powerpoint" },
            { ".pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12" },
            { ".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
            { ".psd", "image/vnd.adobe.photoshop" },
            { ".txt", PlainText },
            { ".wav", "audio/x-wav" },
            { ".weba", "audio/webm" },
            { ".webm", "video/webm" },
            { ".webp", "image/webp" },
            { ".wm", "video/x-ms-wm" },
            { ".wma", "audio/x-ms-wma" },
            { ".xla", "application/vnd.ms-excel" },
            { ".xlam", "application/vnd.ms-excel.addin.macroenabled.12" },
            { ".xlc", "application/vnd.ms-excel" },
            { ".xlm", "application/vnd.ms-excel" },
            { ".xls", "application/vnd.ms-excel" },
            { ".xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12" },
            { ".xlsm", "application/vnd.ms-excel.sheet.macroenabled.12" },
            { ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
            { ".xlt", "application/vnd.ms-excel" },
            { ".xltm", "application/vnd.ms-excel.template.macroenabled.12" },
            { ".xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
            { ".xlw", "application/vnd.ms-excel" },
            { ".xml", "application/xml" },
            { ".zip", "application/zip" },
        };

        public const string JSON = "application/json";
        public const string PlainText = "text/plain";
        public const string OctetStream = "application/octet-stream";
        public const string UrlEncodedForm = "application/x-www-form-urlencoded";
        public const string MultipartFormData = "multipart/form-data; boundary=";
        public const string MultipartByteRanges = "multipart/byteranges; boundary=";
    }
}