namespace Poly.Interpretation.VirtualMachine;

internal enum OpCode : byte {
    Nop,
    Dup, Pop,
    PushInt,
    PushLong,
    PushDouble,
    LoadConst,
    LoadArg,
    LoadLocal,
    StoreLocal,
    LoadValue,
    StoreValue,
    Add, Sub, Mul, Div, Mod, Neg,
    UDiv, UMod,
    Eq, Ne, Lt, Le, Gt, Ge,
    ULt, ULe, UGt, UGe,
    DAdd, DSub, DMul, DDiv, DNeg,
    DEq, DNe, DLt, DLe, DGt, DGe,
    Narrow,
    Jump,
    JumpIfFalse,
    Call,
    CallExternal,
    Return,
    Not,
    IsNull,
    StoreArg,
    Throw,
    EndFinally,
    Int,
    Iret,
    AllocateClosure,
    CallClosure,
    LoadUpvalue,
    StoreUpvalue,
    StrConcat,
    EnumeratorMoveNext,
}