namespace Poly.Interpretation.Analysis.LoweringPrep;

using Poly.Interpretation.Analysis.Semantics;
using Poly.Interpretation.Vm.Instructions;
using Poly.Introspection;
using Poly.Introspection.CommonLanguageRuntime;
using Poly.Syntax;
using Poly.Syntax.Analysis;
using Poly.Syntax.Nodes;

/// <summary>Stores per-node µop fragments generated by <see cref="UopGenerationPass"/>.</summary>
/// <param name="Uops">The µops emitted for this node.</param>
public sealed record LoweredUopMetadata(List<Instruction> Uops) : IAnalysisMetadata;

/// <summary>
/// Generates µop fragments for each AST node and stores them as
/// <see cref="LoweredUopMetadata"/>.  Labels use Pass-2 IDs (unresolved).
/// Variable scope is tracked per Lambda boundary.
/// </summary>
internal sealed class UopGenerationPass : INodeAnalyzer {
    // ── Per-Lambda scope state ──────────────────────────────────────
    private readonly Dictionary<string, int> _params = new();
    private readonly Dictionary<string, int> _locals = new();
    private int _currentArgSlots;

    private sealed record ScopeState(
        Dictionary<string, int> Params,
        Dictionary<string, int> Locals,
        int ArgSlots
    );

    private readonly Stack<ScopeState> _scopeStack = new();

    private void PushScope(Lambda lam) {
        _scopeStack.Push(new ScopeState(
            new Dictionary<string, int>(_params),
            new Dictionary<string, int>(_locals),
            _currentArgSlots
        ));
        _params.Clear();
        _locals.Clear();
    }

    private void PopScope() {
        var prev = _scopeStack.Pop();
        _params.Clear();
        _locals.Clear();
        foreach (var kv in prev.Params) _params[kv.Key] = kv.Value;
        foreach (var kv in prev.Locals) _locals[kv.Key] = kv.Value;
        _currentArgSlots = prev.ArgSlots;
    }

    private int GetOrCreateLocalSlot(string name) {
        if (_params.TryGetValue(name, out int pIdx)) return pIdx;
        if (_locals.TryGetValue(name, out int lIdx)) return _currentArgSlots + 1 + lIdx;
        lIdx = _locals.Count;
        _locals[name] = lIdx;
        return _currentArgSlots + 1 + lIdx;
    }

    private void RegisterParameters(IReadOnlyList<Parameter> parameters) {
        for (int i = 0; i < parameters.Count; i++) {
            if (parameters[i].Name is { } name && !_params.ContainsKey(name))
                _params[name] = i;
        }
        _currentArgSlots = parameters.Count;
    }

    // ── Analyze ─────────────────────────────────────────────────────

    public void Analyze(AnalysisContext context, Node node) {
        if (!context.TryBeginAnalyzerVisit<UopGenerationPass>(node))
            return;

        // ── Node replacement check (constant folding, etc.) ──
        if (context.GetNodeReplacement(node) is Node replacement) {
            Analyze(context, replacement);
            // Copy metadata from replacement to original so lookups by either key succeed.
            var replUops = context.GetMetadata<LoweredUopMetadata>(replacement);
            if (replUops is not null)
                context.SetMetadata(node, replUops);
            return;
        }

        if (node is Lambda lam) PushScope(lam);

        var uops = EmitThis(context, node);
        context.SetMetadata(node, new LoweredUopMetadata(uops));

        if (node is Lambda) PopScope();
    }

    // ── Get child µops (recursively emit if needed) ─────────────────

    private List<Instruction> GetChildUops(AnalysisContext context, Node? child) {
        if (child is null) return [];

        // Follow analysis replacements (constant folding, etc.)
        var actual = context.GetNodeReplacement(child) ?? child;

        var existing = context.GetMetadata<LoweredUopMetadata>(actual);
        if (existing is not null) return existing.Uops;

        Analyze(context, actual);
        var after = context.GetMetadata<LoweredUopMetadata>(actual);
        return after?.Uops ?? [];
    }

    // ── Main dispatch ───────────────────────────────────────────────

    private List<Instruction> EmitThis(AnalysisContext context, Node node) {
        return node switch {
            Constant c => EmitConstant(c),
            Variable v => EmitVariable(v),
            Parameter p => EmitParameter(context, p),
            ThisReference => [new LoadConst(0L) { SourceNodeId = node.Id }],

            Add a => EmitBinary(context, a.LeftHandValue, a.RightHandValue, BinOpKind.Add, a),
            Subtract s => EmitBinary(context, s.LeftHandValue, s.RightHandValue, BinOpKind.Sub, s),
            Multiply m => EmitBinary(context, m.LeftHandValue, m.RightHandValue, BinOpKind.Mul, m),
            Divide d => EmitBinary(context, d.LeftHandValue, d.RightHandValue, BinOpKind.Div, d),
            Modulo mo => EmitBinary(context, mo.LeftHandValue, mo.RightHandValue, BinOpKind.Mod, mo),

            Equal e => EmitBinary(context, e.LeftHandValue, e.RightHandValue, BinOpKind.Eq, e),
            NotEqual ne => EmitBinary(context, ne.LeftHandValue, ne.RightHandValue, BinOpKind.Ne, ne),
            LessThan lt => EmitBinary(context, lt.LeftHandValue, lt.RightHandValue, BinOpKind.Lt, lt),
            LessThanOrEqual le => EmitBinary(context, le.LeftHandValue, le.RightHandValue, BinOpKind.Le, le),
            GreaterThan gt => EmitBinary(context, gt.LeftHandValue, gt.RightHandValue, BinOpKind.Gt, gt),
            GreaterThanOrEqual ge => EmitBinary(context, ge.LeftHandValue, ge.RightHandValue, BinOpKind.Ge, ge),

            And and => EmitBinary(context, and.LeftHandValue, and.RightHandValue, BinOpKind.And, and),
            Or or => EmitBinary(context, or.LeftHandValue, or.RightHandValue, BinOpKind.Or, or),

            BitwiseAnd ba => EmitBinary(context, ba.LeftHandValue, ba.RightHandValue, BinOpKind.And, ba),
            BitwiseOr bor => EmitBinary(context, bor.LeftHandValue, bor.RightHandValue, BinOpKind.Or, bor),
            BitwiseXor bx => EmitBinary(context, bx.LeftHandValue, bx.RightHandValue, BinOpKind.Xor, bx),
            ShiftLeft sl => EmitBinary(context, sl.LeftHandValue, sl.RightHandValue, BinOpKind.Shl, sl),
            ShiftRight sr => EmitBinary(context, sr.LeftHandValue, sr.RightHandValue, BinOpKind.Shr, sr),

            UnaryMinus um => [
                .. GetChildUops(context, um.Operand),
                new BinOp(BinOpKind.Sub, Immediate: 0) { SourceNodeId = um.Id }
            ],
            Not n => EmitUnary(context, n.Value, UnaryOpKind.Not, n),
            BitwiseNot bn => EmitUnary(context, bn.Operand, UnaryOpKind.BitNot, bn),

            Coalesce => EmitBinary(context, node),
            NullForgiving nf => GetChildUops(context, nf.Operand),

            TypeCast tc => GetChildUops(context, tc.Operand),
            TypeIs ti => [
                .. GetChildUops(context, ti.Operand),
                new LoadConst(1L) { SourceNodeId = ti.Id }
            ],
            TypeAs ta => GetChildUops(context, ta.Operand),

            Assignment a => EmitAssignment(context, a),
            Block b => EmitBlock(context, b),
            IfStatement iff => EmitIfStatement(context, iff),
            WhileLoop wl => EmitWhileLoop(context, wl),
            DoWhileLoop dwl => EmitDoWhileLoop(context, dwl),
            ForLoop fl => EmitForLoop(context, fl),
            Conditional cond => EmitConditional(context, cond),

            Lambda lam => EmitLambda(context, lam),
            Invoke inv => EmitInvoke(context, inv),
            Return ret => EmitReturn(context, ret),

            BreakStatement => [new Jump(0) { SourceNodeId = node.Id }],
            ContinueStatement => [new Jump(0) { SourceNodeId = node.Id }],

            Member m => EmitMember(context, m),
            IndexAccess ia => EmitIndexAccess(context, ia),

            New n => [
                .. n.Arguments.SelectMany(a => GetChildUops(context, a)),
                new LoadConst(0L) { SourceNodeId = n.Id }
            ],
            NewArray na => [
                .. GetChildUops(context, na.Length),
                new LoadConst(0L) { SourceNodeId = na.Id }
            ],

            ThrowStatement thr => GetChildUops(context, thr.Exception),
            SuspendNode sn => GetChildUops(context, sn.Inner),
            Await aw => GetChildUops(context, aw.Operand),

            Default d => [new LoadConst(0L) { SourceNodeId = d.Id }],

            _ => [new Nop { SourceNodeId = node.Id }],
        };
    }

    // ── Constant ────────────────────────────────────────────────────

    private static List<Instruction> EmitConstant(Constant c) {
        long value = c.Value switch {
            long lv => lv,
            int iv => iv,
            short sv => sv,
            byte bv => bv,
            bool bvv => bvv ? 1L : 0L,
            uint uiv => (long)uiv,
            _ => 0L,
        };
        return [new LoadConst(value) { SourceNodeId = c.Id }];
    }

    // ── Variable / Parameter ────────────────────────────────────────

    private List<Instruction> EmitVariable(Variable v) {
        return [new LoadSlot(GetOrCreateLocalSlot(v.Name)) { SourceNodeId = v.Id }];
    }

    private List<Instruction> EmitParameter(AnalysisContext context, Parameter p) {
        if (p.DefaultValue is not null)
            return GetChildUops(context, p.DefaultValue);
        return [new LoadSlot(GetOrCreateLocalSlot(p.Name ?? "")) { SourceNodeId = p.Id }];
    }

    // ── Binary / Unary ──────────────────────────────────────────────

    private List<Instruction> EmitBinary(AnalysisContext context, Node left, Node right, BinOpKind kind, Node source) {
        return [
            .. GetChildUops(context, left),
            .. GetChildUops(context, right),
            new BinOp(kind) { SourceNodeId = source.Id }
        ];
    }

    private List<Instruction> EmitBinary(AnalysisContext context, Node node) {
        // Fallback for generic binary nodes
        var left = node.Children.ElementAtOrDefault(0);
        var right = node.Children.ElementAtOrDefault(1);
        return [
            .. GetChildUops(context, left),
            .. GetChildUops(context, right),
            new Nop { SourceNodeId = node.Id }
        ];
    }

    private List<Instruction> EmitUnary(AnalysisContext context, Node operand, UnaryOpKind kind, Node source) {
        return [
            .. GetChildUops(context, operand),
            new UnaryOp(kind) { SourceNodeId = source.Id }
        ];
    }

    // ── Assignment ──────────────────────────────────────────────────

    private List<Instruction> EmitAssignment(AnalysisContext context, Assignment a) {
        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, a.Value));

        if (a.Destination is Variable v) {
            int slot = GetOrCreateLocalSlot(v.Name);
            uops.Add(new StoreSlot(slot) { SourceNodeId = a.Id });
            uops.Add(new LoadSlot(slot) { SourceNodeId = a.Id });
        }
        else if (a.Destination is IndexAccess ia) {
            uops.AddRange(GetChildUops(context, ia.Value));
            uops.AddRange(ia.Arguments.SelectMany(arg => GetChildUops(context, arg)));
            uops.Add(new ArrayStore { SourceNodeId = a.Id });
        }
        else if (a.Destination is Member m) {
            uops.AddRange(GetChildUops(context, m.Value));
            uops.Add(new PopOp { SourceNodeId = a.Id });
            uops.Add(new StoreSlot(GetOrCreateLocalSlot(m.MemberName)) { SourceNodeId = a.Id });
        }
        else {
            uops.Add(new PopOp { SourceNodeId = a.Id });
        }

        return uops;
    }

    // ── Block ───────────────────────────────────────────────────────

    private List<Instruction> EmitBlock(AnalysisContext context, Block block) {
        var uops = new List<Instruction>();

        foreach (var v in block.Variables) {
            if (v is Variable var && !_params.ContainsKey(var.Name) && !_locals.ContainsKey(var.Name)) {
                _locals[var.Name] = _locals.Count;
                int slot = GetOrCreateLocalSlot(var.Name);
                uops.Add(new LoadConst(0L) { SourceNodeId = var.Id });
                uops.Add(new StoreSlot(slot) { SourceNodeId = var.Id });
            }
        }

        for (int i = 0; i < block.Nodes.Count; i++) {
            uops.AddRange(GetChildUops(context, block.Nodes[i]));
            if (i < block.Nodes.Count - 1 && block.Nodes[i] is Poly.Syntax.Nodes.Expression)
                uops.Add(new PopOp { SourceNodeId = block.Id });
        }

        return uops;
    }

    // ── IfStatement ─────────────────────────────────────────────────

    private List<Instruction> EmitIfStatement(AnalysisContext context, IfStatement iff) {
        var labels = context.GetMetadata<IfLabelMetadata>(iff);
        if (labels is null) return [new Nop { SourceNodeId = iff.Id }];

        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, iff.Condition));

        if (iff.ElseBranch is not null && labels.ElseLabel is { } elseLabel) {
            uops.Add(new BranchIfFalse(elseLabel) { SourceNodeId = iff.Id });
            uops.AddRange(GetChildUops(context, iff.ThenBranch));
            uops.Add(new PopOp { SourceNodeId = iff.Id });
            uops.Add(new Jump(labels.EndLabel) { SourceNodeId = iff.Id });
            uops.AddRange(GetChildUops(context, iff.ElseBranch));
            uops.Add(new PopOp { SourceNodeId = iff.Id });
        }
        else {
            uops.Add(new BranchIfFalse(labels.EndLabel) { SourceNodeId = iff.Id });
            uops.AddRange(GetChildUops(context, iff.ThenBranch));
            uops.Add(new PopOp { SourceNodeId = iff.Id });
        }

        return uops;
    }

    // ── WhileLoop ───────────────────────────────────────────────────

    private List<Instruction> EmitWhileLoop(AnalysisContext context, WhileLoop wl) {
        var labels = context.GetMetadata<WhileLoopLabelMetadata>(wl);
        if (labels is null) return [new Nop { SourceNodeId = wl.Id }];

        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, wl.Condition));
        uops.Add(new BranchIfFalse(labels.EndLabel) { SourceNodeId = wl.Id });
        uops.AddRange(GetChildUops(context, wl.Body));
        uops.Add(new PopOp { SourceNodeId = wl.Id });
        uops.Add(new Jump(labels.ContLabel) { SourceNodeId = wl.Id });
        return uops;
    }

    // ── DoWhileLoop ─────────────────────────────────────────────────

    private List<Instruction> EmitDoWhileLoop(AnalysisContext context, DoWhileLoop dwl) {
        var labels = context.GetMetadata<DoWhileLoopLabelMetadata>(dwl);
        if (labels is null) return [new Nop { SourceNodeId = dwl.Id }];

        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, dwl.Body));
        uops.Add(new PopOp { SourceNodeId = dwl.Id });
        uops.AddRange(GetChildUops(context, dwl.Condition));
        uops.Add(new BranchIfFalse(labels.EndLabel) { SourceNodeId = dwl.Id });
        uops.Add(new Jump(labels.ContLabel) { SourceNodeId = dwl.Id });
        return uops;
    }

    // ── ForLoop ─────────────────────────────────────────────────────

    private List<Instruction> EmitForLoop(AnalysisContext context, ForLoop fl) {
        var labels = context.GetMetadata<ForLoopLabelMetadata>(fl);
        if (labels is null) return [new Nop { SourceNodeId = fl.Id }];

        var uops = new List<Instruction>();
        if (fl.Initializer is not null) {
            uops.AddRange(GetChildUops(context, fl.Initializer));
            uops.Add(new PopOp { SourceNodeId = fl.Id });
        }
        if (fl.Condition is not null) {
            uops.AddRange(GetChildUops(context, fl.Condition));
            uops.Add(new BranchIfFalse(labels.EndLabel) { SourceNodeId = fl.Id });
        }
        uops.AddRange(GetChildUops(context, fl.Body));
        uops.Add(new PopOp { SourceNodeId = fl.Id });
        if (fl.Increment is not null) {
            uops.AddRange(GetChildUops(context, fl.Increment));
            uops.Add(new PopOp { SourceNodeId = fl.Id });
        }
        uops.Add(new Jump(labels.CondLabel) { SourceNodeId = fl.Id });
        return uops;
    }

    // ── Conditional ─────────────────────────────────────────────────

    private List<Instruction> EmitConditional(AnalysisContext context, Conditional cond) {
        var labels = context.GetMetadata<ConditionalLabelMetadata>(cond);
        if (labels is null) return [new Nop { SourceNodeId = cond.Id }];

        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, cond.Condition));
        uops.Add(new BranchIfFalse(labels.FalseLabel) { SourceNodeId = cond.Id });
        uops.AddRange(GetChildUops(context, cond.IfTrue));
        uops.Add(new Jump(labels.EndLabel) { SourceNodeId = cond.Id });
        // falseLabel position
        uops.AddRange(GetChildUops(context, cond.IfFalse));
        // endLabel position
        return uops;
    }

    // ── Lambda ──────────────────────────────────────────────────────

    private List<Instruction> EmitLambda(AnalysisContext context, Lambda lam) {
        if (lam.Parameters is not null)
            RegisterParameters(lam.Parameters);

        var uops = new List<Instruction>();
        uops.AddRange(GetChildUops(context, lam.Body));
        uops.Add(new ReturnOp { SourceNodeId = lam.Id });
        return uops;
    }

    // ── Invoke ──────────────────────────────────────────────────────

    private List<Instruction> EmitInvoke(AnalysisContext context, Invoke inv) {
        var resolved = context.GetResolvedMember(inv);

        if (resolved is ClrMethod clrMethod) {
            bool isStatic = clrMethod.IsStatic;
            int argCount = clrMethod.MethodInfo.GetParameters().Length + (isStatic ? 0 : 1);
            return [
                .. inv.Arguments.SelectMany(a => GetChildUops(context, a)),
                new CallExternalDirect(clrMethod.MethodInfo, argCount, isStatic) { SourceNodeId = inv.Id }
            ];
        }

        if (resolved is ClrConstructor clrCtor) {
            return [
                .. inv.Arguments.SelectMany(a => GetChildUops(context, a)),
                new CallExternal(0, inv.Arguments.Length) { SourceNodeId = inv.Id }
            ];
        }

        if (resolved is ClrTypeProperty clrProp) {
            bool isStatic = clrProp.IsStatic;
            var getter = clrProp.PropertyInfo.GetGetMethod(nonPublic: true);
            if (getter is not null) {
                int argCount = getter.GetParameters().Length + (isStatic ? 0 : 1);
                if (!isStatic) {
                    var target = inv.Delegate is Member m ? m.Value : new Constant(0L);
                    return [
                        .. GetChildUops(context, target),
                        new CallExternalDirect(getter, argCount, isStatic) { SourceNodeId = inv.Id }
                    ];
                }
                return [
                    new CallExternalDirect(getter, argCount, isStatic) { SourceNodeId = inv.Id }
                ];
            }
            // Fallback
            var fallback = inv.Delegate is Member m2 ? m2.Value : new Constant(0L);
            return [
                .. GetChildUops(context, fallback),
                new LoadConst(0L) { SourceNodeId = inv.Id }
            ];
        }

        if (inv.Delegate is Lambda lambda) {
            // Inline lambda
            int savedArgSlots = _currentArgSlots;
            var savedParams = new Dictionary<string, int>(_params);
            var savedLocals = new Dictionary<string, int>(_locals);

            var uops = new List<Instruction>();

            if (lambda.Parameters is not null) {
                for (int i = 0; i < lambda.Parameters.Count && i < inv.Arguments.Length; i++) {
                    var p = lambda.Parameters[i];
                    if (p.Name is { } name) {
                        if (!_params.ContainsKey(name))
                            _params[name] = i;
                        uops.AddRange(GetChildUops(context, inv.Arguments[i]));
                        uops.Add(new StoreSlot(GetOrCreateLocalSlot(name)) { SourceNodeId = inv.Id });
                    }
                }
            }
            _currentArgSlots = lambda.Parameters?.Count ?? 0;
            uops.AddRange(GetChildUops(context, lambda.Body));
            uops.Add(new ReturnOp { SourceNodeId = lambda.Id });

            _currentArgSlots = savedArgSlots;
            _params.Clear();
            _locals.Clear();
            foreach (var kv in savedParams) _params[kv.Key] = kv.Value;
            foreach (var kv in savedLocals) _locals[kv.Key] = kv.Value;

            return uops;
        }

        if (inv.Delegate is Member member) {
            return [
                .. inv.Arguments.SelectMany(a => GetChildUops(context, a)),
                new Call(0, inv.Arguments.Length) { SourceNodeId = inv.Id }
            ];
        }

        return [
            .. inv.Arguments.SelectMany(a => GetChildUops(context, a)),
            new Call(0, inv.Arguments.Length) { SourceNodeId = inv.Id }
        ];
    }

    // ── Return ──────────────────────────────────────────────────────

    private List<Instruction> EmitReturn(AnalysisContext context, Return ret) {
        if (ret.Value is not null)
            return [
                .. GetChildUops(context, ret.Value),
                new ReturnOp { SourceNodeId = ret.Id }
            ];
        return [new ReturnOp { SourceNodeId = ret.Id }];
    }

    // ── Member (property/method reference) ──────────────────────────

    private List<Instruction> EmitMember(AnalysisContext context, Member m) {
        var resolved = context.GetResolvedMember(m);

        if (resolved is ClrTypeProperty property) {
            var getter = property.PropertyInfo.GetGetMethod(nonPublic: true);
            if (getter is not null) {
                bool isStatic = property.IsStatic;
                int argCount = getter.GetParameters().Length + (isStatic ? 0 : 1);
                if (!isStatic) {
                    return [
                        .. GetChildUops(context, m.Value),
                        new CallExternalDirect(getter, argCount, isStatic) { SourceNodeId = m.Id }
                    ];
                }
                return [
                    new CallExternalDirect(getter, argCount, isStatic) { SourceNodeId = m.Id }
                ];
            }
        }

        if (resolved is ClrMethod clrGetter) {
            bool isStatic = clrGetter.IsStatic;
            int argCount = clrGetter.MethodInfo.GetParameters().Length + (isStatic ? 0 : 1);
            if (!isStatic) {
                return [
                    .. GetChildUops(context, m.Value),
                    new CallExternalDirect(clrGetter.MethodInfo, argCount, isStatic) { SourceNodeId = m.Id }
                ];
            }
            return [
                new CallExternalDirect(clrGetter.MethodInfo, argCount, isStatic) { SourceNodeId = m.Id }
            ];
        }

        return [
            .. GetChildUops(context, m.Value),
            new LoadConst(0L) { SourceNodeId = m.Id }
        ];
    }

    // ── IndexAccess ─────────────────────────────────────────────────

    private List<Instruction> EmitIndexAccess(AnalysisContext context, IndexAccess ia) {
        return [
            .. GetChildUops(context, ia.Value),
            .. ia.Arguments.SelectMany(a => GetChildUops(context, a)),
            new LoadConst(0L) { SourceNodeId = ia.Id }
        ];
    }
}

public static class UopGenerationExtensions {
    extension(AnalyzerBuilder builder) {
        public AnalyzerBuilder UseUopGeneration() {
            builder.AddAnalyzer(new UopGenerationPass());
            return builder;
        }
    }
}