using Poly.Interpretation.Vm;
using Poly.Introspection.CommonLanguageRuntime;
using Poly.Syntax.Primitives;

namespace Poly.Tests.Interpretation;

/// <summary>
/// Tests for PrimitiveNode Expand — verifying the primitive sequences
/// generated by each AST node before they enter the VM pipeline.
/// </summary>
public class PrimitiveExpandOutputTests {
    private static ExpansionContext MakeCtx() => new(new AnalysisContext(ClrTypeDefinitionRegistry.Shared));

    [Test]
    public async Task Expand_Constant_YieldsPushConstant() {
        var prims = new Constant(42L).ToPrimitives(MakeCtx()).ToArray();
        await Assert.That(prims.Length).IsEqualTo(1);
        await Assert.That(prims[0]).IsTypeOf<PushConstant>();
        await Assert.That(((PushConstant)prims[0]).Value).IsEqualTo(42L);
    }

    [Test]
    public async Task Expand_Add_YieldsLhsRhsBinOp() {
        var prims = new Add(new Constant(1), new Constant(2)).ToPrimitives(MakeCtx()).ToArray();
        await Assert.That(prims.Length).IsEqualTo(3);
        await Assert.That(prims[0]).IsTypeOf<PushConstant>();
        await Assert.That(prims[1]).IsTypeOf<PushConstant>();
        await Assert.That(prims[2]).IsTypeOf<BinaryOp>();
        await Assert.That(((BinaryOp)prims[2]).Op).IsEqualTo(OpKind.Add);
    }

    [Test]
    public async Task Expand_NestedAdd_YieldsCorrectPrimitives() {
        // (1 + 2) + 3
        var prims = new Add(new Add(new Constant(1), new Constant(2)), new Constant(3))
            .ToPrimitives(MakeCtx()).ToArray();

        await Assert.That(prims.Length).IsEqualTo(5);
        // 1, 2, Add, 3, Add
        await Assert.That(prims[0]).IsTypeOf<PushConstant>(); // 1
        await Assert.That(prims[1]).IsTypeOf<PushConstant>(); // 2
        await Assert.That(prims[2]).IsTypeOf<BinaryOp>();     // inner Add
        await Assert.That(prims[3]).IsTypeOf<PushConstant>(); // 3
        await Assert.That(prims[4]).IsTypeOf<BinaryOp>();     // outer Add
    }
}